# Generated by Django 5.1.5 on 2025-01-19 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toth', '0002_remove_usuario_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciasusuario',
            name='profesor_favorito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='toth.profesor'),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contenidos', to='toth.categoriacontenido'),
        ),
    ]
