# Generated by Django 5.1.5 on 2025-01-19 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toth', '0003_preferenciasusuario_profesor_favorito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='usuario',
        ),
        migrations.AddField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(default='Profesor genérico', max_length=100),
        ),
        migrations.AlterField(
            model_name='preferenciasusuario',
            name='profesor_favorito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='toth.profesor'),
        ),
    ]
