# Generated by Django 5.1.5 on 2025-01-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toth', '0007_datospersonales_delete_preferenciasusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenido',
            old_name='video',
            new_name='video_url',
        ),
        migrations.AddField(
            model_name='contenido',
            name='video_archivo',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
