# Generated by Django 5.1.5 on 2025-01-21 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toth', '0009_alter_categoriacontenido_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseRealizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizacion', models.DateField(auto_now_add=True)),
                ('realizada', models.BooleanField(default=False)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realizaciones', to='toth.clase')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('contenido_adjunto', models.FileField(blank=True, null=True, upload_to='feedback_adjuntos/')),
                ('puntuacion_contenidos', models.JSONField(blank=True, help_text='Debe ser un diccionario con el ID del contenido y su puntuación.', null=True)),
                ('clase_realizada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='toth.claserealizada')),
            ],
        ),
    ]
