# Generated by Django 5.1.5 on 2025-01-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toth', '0010_claserealizada_feedbackusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claserealizada',
            name='realizada',
        ),
        migrations.AddField(
            model_name='claserealizada',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de realizarse'), ('realizada', 'Realizada')], default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='claserealizada',
            name='fecha_realizacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
