# Generated by Django 5.1.5 on 2025-01-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toth', '0013_remove_datospersonales_estilo_musical_favorito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
