# Generated by Django 5.1.5 on 2025-01-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toth', '0015_novedad_clasificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='video_archivo',
            field=models.FileField(blank=True, null=True, upload_to='novedades/videos/'),
        ),
    ]
