# Generated by Django 5.1.5 on 2025-01-26 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toth', '0018_pago_clase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriacontenido',
            options={'verbose_name': 'Categoría de contenido', 'verbose_name_plural': 'Categorías de contenido'},
        ),
        migrations.AlterField(
            model_name='pago',
            name='clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='toth.clase'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to=settings.AUTH_USER_MODEL),
        ),
    ]
