# Generated by Django 5.1.5 on 2025-01-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toth', '0019_alter_categoriacontenido_options_alter_pago_clase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='init_point',
            field=models.URLField(blank=True, null=True, verbose_name='URL de MercadoPago'),
        ),
    ]
