# Generated by Django 5.1.5 on 2025-01-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toth', '0020_pago_init_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='estado',
            field=models.BooleanField(choices=[(True, 'Activa'), (False, 'Inactiva')], default=True, verbose_name='Estado'),
        ),
    ]
