# Generated by Django 5.1.5 on 2025-03-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toth', '0021_alter_novedad_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('mercado_pago', 'Mercado Pago'), ('transferencia', 'Transferencia')], default='mercado_pago', max_length=50),
        ),
    ]
