# Generated by Django 5.1.5 on 2025-03-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toth', '0023_alter_pago_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'ordering': ['orden', 'fecha_inscripcion']},
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='orden',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Orden'),
        ),
    ]
