# Generated by Django 5.1.5 on 2025-04-10 16:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toth', '0024_alter_inscripcion_options_inscripcion_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='archivo_pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='archivo_pdf'),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='video_archivo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video_archivo'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='video_archivo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video_archivo'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='comprobante',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='comprobante'),
        ),
    ]
