# Generated by Django 5.1.5 on 2025-05-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toth', '0025_alter_contenido_archivo_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='color_footer_text',
            field=models.CharField(blank=True, help_text='Color del texto del footer en formato HEX (ej: #ffffff)', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='color_header',
            field=models.CharField(blank=True, help_text='Color del header en formato HEX (ej: #ff5733)', max_length=7, null=True),
        ),
    ]
