# Generated by Django 5.1.5 on 2025-05-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toth', '0026_profesor_color_footer_text_profesor_color_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='color_footer',
            field=models.CharField(blank=True, help_text='Color del fondo del footer en formato HEX (ej: #171d1e)', max_length=7, null=True),
        ),
    ]
